- date: 2020-04-06T20:59:43.10-03:00
  tags:
    - MQTT
  color: red
  message: It is a test MQTT Down.
  
- date: 2020-04-06T20:59:43.10-03:00
  tags:
    - SMS
  color: orange
  message: It is a test at SMS unstable.
  
- date: 2020-04-05T20:59:43.10-03:00
  tags:
    - MQTT
  color: green
  message: It is a test at 05.

- date: 2020-04-04T05:59:43.10-03:00
  tags:
    - SMS
    - E-Mail
  color: orange
  message: It is a test at 04.

- date: 2020-04-03T09:59:43.10-03:00
  tags:
    - SMS
    - E-Mail
  color: red
  message: It is a test at 03.

- date: 2020-04-03T10:30:43.10-03:00
  tags:
    - SMS
    - E-Mail
  color: green
  message: It is a test at 03 green.
  
  
- date: 2020-01-03T10:30:43.10-03:00
  tags:
    - SMS
    - E-Mail
  color: red
  message: It is a test at 01-03 green.
