- date: 2020-11-25T20:15:00.10-03:00
  tags:
    - Api
  color: green
  message: Instability was resolved, the AWS was down. We are monitoring continuously.
  
- date: 2020-11-25T13:00:00.10-03:00
  tags:
    - Api
  color: orange
  message: An Amazon AWS outage is currently impacting TagoIO so you may be having issues accessing your dashboards. We are actively working with AWS and will report when the issue has subsided. We apologize for any inconvenience!

- date: 2020-10-10T19:31:00.10-03:00
  tags:
    - Api
  color: green
  message: Instability was resolved, the AWS was down on all South America.

- date: 2020-10-10T19:00:00.10-03:00
  tags:
    - Api
  color: orange
  message: Fixed-IP temporary disabled to allow connection with South America.

- date: 2020-10-10T18:45:00.10-03:00
  tags:
    - Api
  color: red
  message: South America servers not accessible.

- date: 2020-10-09T13:29:00.10-03:00
  tags:
    - Analysis
  color: green
  message: Instability was resolved.

- date: 2020-10-09T13:10:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: Execution error rate for Analyses is at 12%. We continue to monitor the situation.

- date: 2020-10-09T12:40:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: The cause for the delay is a network issue in our cloud provider. We are closely monitoring the situation and doing everything we can to normalize execution times.

- date: 2020-10-09T12:20:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: Some Analyses are back to a normal execution time, we continue to work towards normalizing all Analyses.

- date: 2020-10-09T12:00:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: We are still investigating delayed execution times for Analyses.

- date: 2020-10-09T11:45:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: Analyses executions are unstable.

- date: 2020-09-21T10:40:00.10-03:00
  tags:
    - Api
  color: green
  message: Issue was solved.

- date: 2020-09-21T10:39:00.10-03:00
  tags:
    - Api
  color: red
  message: Downtime in TagoIO servers.
 
- date: 2020-07-16T12:01:00.10-03:00
  tags:
    - Api
  color: green
  message: Issue was solved.

- date: 2020-07-16T11:49:00.10-03:00
  tags:
    - Api
  color: orange
  message: The root of the issue was in the bucket data delete queue, causing denial of service of the API.

- date: 2020-07-16T10:22:00.10-03:00
  tags:
    - Api
  color: orange
  message: Issue was found, some customers may have been affected with an unresponsive API or with the error Bucket database unavailable.

- date: 2020-07-16T10:07:00.10-03:00
  tags:
    - Api
  color: orange
  message: We are investigating instability on the API.

- date: 2020-04-29T13:55:00.10-03:00
  tags:
    - Analysis
  color: green
  message: Issue with Analysis Service was solved.

- date: 2020-04-29T13:40:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: We are investigating elevated errors for Analysis service.

- date: 2020-04-29T13:35:00.10-03:00
  tags:
    - Analysis
  color: red
  message: Analysis service is unstable.
