- date: 2020-07-16T12:01:00.10-03:00
  tags:
    - Api
  color: green
  message: Issue was solved.

- date: 2020-07-16T11:49:00.10-03:00
  tags:
    - Api
  color: orange
  message: The root of the issue was in the bucket's data delete queue, causing denial of service of the API.

- date: 2020-07-16T10:22:00.10-03:00
  tags:
    - Api
  color: orange
  message: Issue was found, some customers may have been affected with an unresponsive API or with this error: Bucket database unavailable.
  
- date: 2020-07-16T10:07:00.10-03:00
  tags:
    - Api
  color: orange
  message: We are investigating instability on the API.

- date: 2020-04-29T13:55:00.10-03:00
  tags:
    - Analysis
  color: green
  message: Issue with Analysis Service was solved.

- date: 2020-04-29T13:40:00.10-03:00
  tags:
    - Analysis
  color: orange
  message: We are investigating elevated errors for Analysis service.

- date: 2020-04-29T13:35:00.10-03:00
  tags:
    - Analysis
  color: red
  message: Analysis service is unstable.
